Update usage for v12
ArasLabs/call-date-dialog pull request #10
Opened 2019-08-01 20:33 UTC by sampoearas

- update readme with v12 usage/screenshot

2019-08-01 21:57 UTC, EliJDonahue requested changes

2019-08-01 21:57 UTC, EliJDonahue commented on README.md
> +1. Aras Innovator installed (current released version preferred)
```suggestion
1. Aras Innovator installed (see "Supported Aras Versions" above)
```

2019-08-01 21:57 UTC, EliJDonahue commented on README.md
> +![Date Dialog Steps](./Screenshots/v12-action_steps.png)
Let's make this a gif. Name it 12-demo.gif and rename the old one to 11-demo.gif. Keep the old gif in the screenshots folder for reference, but only show the new one in the readme.

2019-08-02 13:23 UTC, sampoearas commented
Updated readme per suggestions

2019-08-02 21:20 UTC, EliJDonahue approved these changes

2019-08-02 21:21 UTC, EliJDonahue approved these changes

2019-08-05 12:57 UTC, merged